obj_player.canmove = 0
audio_stop_sound(sfx_mach3)
audio_stop_sound(sfx_mach2)
draw_set_font(fnt_font)
draw_set_colour(c_white)
draw_set_halign(fa_center)
draw_set_valign(fa_middle)
draw_text(480, 270, message)
draw_set_halign(fa_left)
draw_set_valign(fa_top)
